version: "3.7"

services:

  explorer_web:
    hostname: explorer-web
    container_name: explorer-web
    build:
      context: ../frontend
      dockerfile: Dockerfile
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for explorer-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 80:8080
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "explorer-api"
      TESTNET_ENABLED: true
      MAINNET_ENABLED: true
      ROOT_NETWORK: testnet
      
  explorer_api:
    hostname: explorer-api
    container_name: explorer-api
    build:
      context: .
      dockerfile: backend/Dockerfile
      additional_contexts:
        backend: ../backend
        rustgbt: ../rust/gbt
    environment:
      MEMPOOL_STDOUT_LOG_MIN_PRIORITY: "debug"
      MEMPOOL_BLOCKS_SUMMARIES_INDEXING: true

      MEMPOOL_NETWORK: "testnet"

      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "<ELECTRUM_HOST:50001>"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"

      MEMPOOL_AUTOMATIC_POOLS_UPDATE: true
      MEMPOOL_POOLS_JSON_URL: "https://raw.githubusercontent.com/myfloki/community-tools/main/assets/pools.json"

      CORE_RPC_HOST: "<FLOKICOIN_NODE_HOST>"
      CORE_RPC_PORT: "15213"
      CORE_RPC_USERNAME: "user"
      CORE_RPC_PASSWORD: "pass"

      DATABASE_ENABLED: "true"
      DATABASE_HOST: "explorer-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"

      STATISTICS_ENABLED: "true"
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh explorer-db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data/api:/backend/cache

  explorer_db:
    hostname: explorer-db
    container_name: explorer-db
    image: mariadb:10.5.21
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ./data/mysql:/var/lib/mysql
